# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.URLField()),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('story', models.CharField(max_length=5000)),
                ('bio', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=30)),
                ('affiliation', models.CharField(max_length=50)),
                ('base_of_operation', models.CharField(max_length=50)),
                ('avatar', models.URLField()),
                ('large_avatar', models.URLField()),
                ('abilities', models.ManyToManyField(to='app.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField()),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('source', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='media',
            field=models.ManyToManyField(to='app.Media'),
        ),
    ]
