# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='media',
        ),
        migrations.AddField(
            model_name='ability',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Hero'),
        ),
        migrations.AddField(
            model_name='media',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Hero'),
        ),
    ]
